[package]
name = "profiler-get-symbols"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
pdb = "0.3.0"
scroll = "0.9.2"
uuid = "0.7.2"
js-sys = "0.3.25"
wasm-bindgen = {version = "0.2.48", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.3.25"
futures = "0.1.20"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "^1.0.59"
serde_json = "1.0"
json = "*"
futures-macro-await = "0.2.1"
futures-stable = "0.2.1"
# futures-await = "0.1"

[dependencies.object]
version = "0.10.0"
default-features = false
features = ["std"]

[dependencies.goblin]
# The version and features of goblin need to match what's in object's Cargo.toml,
# because we really want object's goblin and not another instance of goblin.
version = "0.0.17"
features = ["endian_fd", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "archive"]
default-features = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
